### ISSUE TITLE
llvm build fails with a std::atomic check error 

### ISSUE THREAD

**Issue by RavikumarTulugu** [medvid/make-rootfs#2]
I am using clang-13 which comes with the ubuntu imprish distro. the cmake of llvm fails with a strange std::atomic error. some reason the cmake falsely decides the host compiler is not std::atomic support. I guess you need to adjust the CMAKE flags a bit for  this.

**Comment by RavikumarTulugu** [comment]
this happens when we issue a make with out any arguments in the top most folder. make bootstrap seems to work fine.

**Comment by medvid** [comment]
All make targets except for stage1-stage4 bootstrapping and 'builtins', have to be executed inside the chroot.

The bootstrap sequence is the following:

```
make bootstrap
make builtins
make chroot
# inside chroot:
make
make install
```

While it is possible to detect if the non-bootstrap target is executed from the host system (by inspecting MAKECMDGOALS and CURDIR), I decided to avoid such check for simplicity (sometimes I test some packages directly from ubuntu host, without chroot).

**Comment by medvid** [comment]
this specific issue happens due to chicken-and-egg problem - single plk/llvm.mk builds complete LLVM toolchain as well as the compiler-rt/libcxxabi/libcxx base libraries - as non-bootstrap build always executes with `--sysroot=out/$(TARGET)`, the C/C++ libraries are missing from the target rootfs. There is no easy way to avoid this issue without splitting pkg/llvm.mk into pkg/libcxx.mk, pkg/clang.mk, pkg/compiler-rt.mk - further complicating the LLVM bootstrap.

**Comment by RavikumarTulugu** [comment]
I am trying to build a custom distro for beaglebone and was re-using some of your work. my problem is simpler, i need to build a rootfs with toybox and opkg and am done. the above problem goes away if we guide the cmake by CC and CXX variables.
